name: ParER Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-wf-template:
    uses: RegioneER/parer-github-template/.github/workflows/wf-template.yml@v2
    with:
      java: '11'
      publiccode-file: 'publiccode.yml'
      run-publiccode-validation: false
    secrets:
      CI_PARERWORKER_RW_TOKEN: ${{ secrets.CI_PARERWORKER_RW_TOKEN }}
